services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: appuser
    ports:
      - 5435:5435

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8085
